"""empty message

Revision ID: 2a84ad689786
Revises: ac2e30e9a352
Create Date: 2018-02-11 22:57:16.185876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a84ad689786'
down_revision = 'ac2e30e9a352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'title')
    # ### end Alembic commands ###
