"""empty message

Revision ID: 8de40efc9822
Revises: 967c6b16d543
Create Date: 2018-02-11 16:40:34.346264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de40efc9822'
down_revision = '967c6b16d543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('in_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'in_use')
    # ### end Alembic commands ###
