"""empty message

Revision ID: 967c6b16d543
Revises: 6a87e32f6248
Create Date: 2018-02-11 16:29:15.273592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967c6b16d543'
down_revision = '6a87e32f6248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_numbers')
    # ### end Alembic commands ###
