"""empty message

Revision ID: ac2e30e9a352
Revises: 8de40efc9822
Create Date: 2018-02-11 17:00:32.866942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2e30e9a352'
down_revision = '8de40efc9822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('choices', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'choices')
    # ### end Alembic commands ###
